import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Image from "next/image";
import { cn } from "@/utils/classNames";
import { layout } from "./layout.css";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={cn(roboto.className, layout)}>
        <Image
          alt="Logo ECO"
          src="/logo.png"
          width={512}
          height={512}
          style={{
            zIndex: "-1",
            position: "fixed",
            bottom: -90,
            right: -120,
          }}
        />
        {children}
      </body>
    </html>
  );
}
